version: "3.5"
services:
  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    env_file:
      - .bpr_env
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
  web:
    image: php:apache
    restart: always
    container_name: web
    env_file:
      - .bpr_env
    volumes:
      - ./html:/var/www/html
    build: 
      context: .
      dockerfile: web.dockerfile
    depends_on:
      - mariadb
    ports:
      - 8880:80
    links:
      - mariadb
    stdin_open: true
    tty: true